parameters:
    core_main_layout: 'OCCoreBundle::layout.html.twig'
services:
#    oc_core.example:
#        class: OC\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]